services:
  db:
    image: postgres:latest
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development

  web:
    build: .
    command: bash -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium
    platform: linux/amd64
    environment:
      CHROME_DRIVER_URL: http://selenium:4444/wd/hub

  selenium:
    image: selenium/standalone-chromium:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

volumes:
  postgres_data: