daily:
  - content: "成功は失敗の反対ではなく、継続の結果である"
    author: "スティーブン・リチャーズ"
  - content: "努力は天才を凌駕する"
    author: "石川啄木"
  - content: "成功は成功を信じる者に訪れる"
    author: "ウィリアム・ジェームズ"
  - content: "小さなことの積み重ねが、大きな結果を生む"
    author: "オグ・マンディーノ"
  - content: "一歩前進することが、すべてを変える"
    author: "リチャード・ブランソン"
  - content: "挑戦する者にしかチャンスは訪れない"
    author: "ハーバート・フーバー"
  - content: "目標を見失わなければ、道は開ける"
    author: "フィリップ・コトラー"
  - content: "忍耐は成功の鍵である"
    author: "ヘンリー・フォード"
  - content: "毎日少しずつでも前進することが、成功の道"
    author: "アリストテレス"
  - content: "習慣が運命を形作る"
    author: "ジョン・ドライデン"
  - content: "明日は今日の努力の結果である"
    author: "アルバート・アインシュタイン"

hourly:
  - content: "時を守り、時を作り、時に従う"
    author: "渋沢栄一"
  - content: "時間は貴重です。無駄にすることはできません"
    author: "ベンジャミン・フランクリン"
  - content: "時間は金よりも貴重である"
    author: "ソクラテス"
  - content: "無駄にした時間を悔やむより、今を生きよう"
    author: "ウィリアム・ペン"
  - content: "今日という日は二度と来ない"
    author: "ヘレン・ケラー"
  - content: "時を愛する者は、永遠を手に入れる"
    author: "ダライ・ラマ"
  - content: "時間を浪費するな、人生はそれの積み重ねだ"
    author: "セネカ"
  - content: "時間は最も公正な財産である"
    author: "リンカーン"
  - content: "成功の秘訣は、毎日を無駄にしないことだ"
    author: "チャールズ・ディケンズ"
  - content: "時を尊重する者は成功を手に入れる"
    author: "レオナルド・ダ・ヴィンチ"
  - content: "今を生きることで、未来が輝く"
    author: "スティーブ・ジョブズ"
  - content: "時間の使い方が、人生の質を決める"
    author: "ヴォルテール"

overdue:
  - content: "今すぐにやる、それが成功の鍵だ"
    author: "ナポレオン・ヒル"
  - content: "過去は戻らない。未来を変えよう"
    author: "マイケル・ジョーダン"
  - content: "最悪の失敗は、行動しないことである"
    author: "ウィリアム・ジェームズ"
  - content: "遅れたとしても、今からでも始めよう"
    author: "マーティン・ルーサー・キング・ジュニア"
  - content: "一度の遅れが、未来の遅れを招く"
    author: "トーマス・ジェファーソン"
  - content: "すべての遅れには理由がある。しかし、それを乗り越えるのが成功者だ"
    author: "オプラ・ウィンフリー"
  - content: "時間は待ってくれない。今を逃すな"
    author: "ラルフ・ワルド・エマーソン"
  - content: "行動しないことが、最大の障害だ"
    author: "エレノア・ルーズベルト"
  - content: "過去は戻らない。未来を取り戻そう"
    author: "ウィンストン・チャーチル"
  - content: "何もしないことが最大の後悔となる"
    author: "マーク・トウェイン"
  - content: "今やらないことが、後で後悔になる"
    author: "ジム・ローン"
  - content: "未来を変えるのは、今の行動である"
    author: "トニー・ロビンズ"
