daily:
  - content: "成功は失敗の反対ではなく、継続の結果である"
    author: "スティーブン・リチャーズ"
  - content: "努力は天才を凌駕する"
    author: "石川啄木"
  - content: "成功は成功を信じる者に訪れる"
    author: "ウィリアム・ジェームズ"
  - content: "小さなことの積み重ねが、大きな結果を生む"
    author: "オグ・マンディーノ"
  - content: "一歩前進することが、すべてを変える"
    author: "リチャード・ブランソン"
  - content: "挑戦する者にしかチャンスは訪れない"
    author: "ハーバート・フーバー"
  - content: "目標を見失わなければ、道は開ける"
    author: "フィリップ・コトラー"
  - content: "忍耐は成功の鍵である"
    author: "ヘンリー・フォード"
  - content: "毎日少しずつでも前進することが、成功の道"
    author: "アリストテレス"
  - content: "習慣が運命を形作る"
    author: "ジョン・ドライデン"
  - content: "明日は今日の努力の結果である"
    author: "アルバート・アインシュタイン"

hourly:
  - content: "時を守り、時を作り、時に従う"
    author: "渋沢栄一"
  - content: "時間は貴重です。無駄にすることはできません"
    author: "ベンジャミン・フランクリン"
  - content: "時間は金よりも貴重である"
    author: "ソクラテス"
  - content: "無駄にした時間を悔やむより、今を生きよう"
    author: "ウィリアム・ペン"
  - content: "今日という日は二度と来ない"
    author: "ヘレン・ケラー"
  - content: "時を愛する者は、永遠を手に入れる"
    author: "ダライ・ラマ"
  - content: "時間を浪費するな、人生はそれの積み重ねだ"
    author: "セネカ"
  - content: "時間は最も公正な財産である"
    author: "リンカーン"
  - content: "成功の秘訣は、毎日を無駄にしないことだ"
    author: "チャールズ・ディケンズ"
  - content: "時を尊重する者は成功を手に入れる"
    author: "レオナルド・ダ・ヴィンチ"
  - content: "今を生きることで、未来が輝く"
    author: "スティーブ・ジョブズ"
  - content: "時間の使い方が、人生の質を決める"
    author: "ヴォルテール"

overdue:
  - content: "今すぐにやる、それが成功の鍵だ"
    author: "ナポレオン・ヒル"
  - content: "過去は戻らない。未来を変えよう"
    author: "マイケル・ジョーダン"
  - content: "最悪の失敗は、行動しないことである"
    author: "ウィリアム・ジェームズ"
  - content: "遅れたとしても、今からでも始めよう"
    author: "マーティン・ルーサー・キング・ジュニア"
  - content: "一度の遅れが、未来の遅れを招く"
    author: "トーマス・ジェファーソン"
  - content: "すべての遅れには理由がある。しかし、それを乗り越えるのが成功者だ"
    author: "オプラ・ウィンフリー"
  - content: "時間は待ってくれない。今を逃すな"
    author: "ラルフ・ワルド・エマーソン"
  - content: "行動しないことが、最大の障害だ"
    author: "エレノア・ルーズベルト"
  - content: "過去は戻らない。未来を取り戻そう"
    author: "ウィンストン・チャーチル"
  - content: "何もしないことが最大の後悔となる"
    author: "マーク・トウェイン"
  - content: "今やらないことが、後で後悔になる"
    author: "ジム・ローン"
  - content: "未来を変えるのは、今の行動である"
    author: "トニー・ロビンズ"

line:
  - content: "問題解決は新たな挑戦への入り口だ。エラーは成長の機会。"
    author: "リーナス・トーバルズ"
  - content: "プログラムは、人間が読めるように書いてこそ真価を発揮する。"
    author: "マーティン・ファウラー"
  - content: "ソフトウェア工学は、失敗することが前提の分野だ。失敗は成功への第一歩。"
    author: "グレース・ホッパー"
  - content: "リスクを恐れず挑戦することが、成功への最初のステップだ。"
    author: "ジェフ・ベゾス"
  - content: "何もしなければ、何も起こらない。それが最も大きなリスクだ。"
    author: "イーロン・マスク"
  - content: "バグが出るのは仕方がない。それをどう修正するかが問題だ。"
    author: "ケン・トンプソン"
  - content: "最初にうまくいかなくても、諦めずに続けることが成功への鍵だ。"
    author: "トーマス・エジソン"
  - content: "変化は避けられない。変化を受け入れ、適応する者が勝つ。"
    author: "ビル・ゲイツ"
  - content: "失敗を恐れず行動する者が、最も成長する。"
    author: "リチャード・ブランソン"
  - content: "アイデアは簡単だ。実行することが難しい。"
    author: "スティーブ・ジョブズ"
  - content: "コードは書く時間の50%、テストと改善の50%。バグを恐れるな、それを乗り越える力をつけよ。"
    author: "グレース・ホッパー"
  - content: "我々はイノベーションを求め続ける。昨日の成功は、明日の成功を保証しない。"
    author: "サティア・ナデラ"
  - content: "成功はリスクを避けていては得られない。行動しなければ何も変わらない。"
    author: "ラリー・ペイジ"
  - content: "成功は継続の結果だ。どんなに小さな進歩でも続けることが重要だ。"
    author: "スティーブ・ウォズニアック"
  - content: "未来はコードの中にある。それを創り出すのは私たちだ。"
    author: "マーク・ザッカーバーグ"
  - content: "失敗することは悪くない。それをどう活かすかが重要だ。"
    author: "トーマス・エジソン"
  - content: "最も大きなリスクは、リスクを取らないことだ。"
    author: "マーク・ザッカーバーグ"
  - content: "学び続けることが、成功の唯一の保証だ。"
    author: "ビル・ゲイツ"
  - content: "すべての成功は、挑戦から始まる。失敗を恐れず挑め。"
    author: "ジェフ・ベゾス"
  - content: "革新は、小さな一歩から生まれる。"
    author: "シュリニヴァーサ・ラマヌジャン"
- content: "諦めたらそこで試合終了ですよ。"
    author: "安西先生（スラムダンク）"
  - content: "人はいつ死ぬと思う？心臓を銃で撃ち抜かれた時？違う！病気で侵された時？違う！…人に忘れられた時さ。"
    author: "ドクター・ヒルルク（ONE PIECE）"
  - content: "僕はこの国に生まれて良かった。"
    author: "ルフィ（ONE PIECE）"
  - content: "努力した者全てが成功するとは限らん。しかし、成功した者は皆すべからく努力しておる。"
    author: "ロイ・マスタング（鋼の錬金術師）"
  - content: "逃げちゃダメだ、逃げちゃダメだ、逃げちゃダメだ！"
    author: "碇シンジ（新世紀エヴァンゲリオン）"
  - content: "人が人を信じることができなくなった時、そこには何も生まれないんだよ。"
    author: "渚カヲル（新世紀エヴァンゲリオン）"
  - content: "命を燃やせ！"
    author: "エース（ONE PIECE）"
  - content: "私は正しいと思ったことをしたまでだ。"
    author: "朽木白哉（BLEACH）"
  - content: "勝ちたいという気持ちが一番大事だ。"
    author: "流川楓（スラムダンク）"
  - content: "このジョルノ・ジョバァーナには『夢』がある！"
    author: "ジョルノ・ジョバァーナ（ジョジョの奇妙な冒険）"
  - content: "『任務は遂行する』『部下も守る』。「両方」やらなくちゃあならないってのが「幹部」のつらいところだな。覚悟はいいか？オレはできてる"
    author: "ブルーノ・ブチャラティ（ジョジョの奇妙な冒険）"
  - content: "人というのは成功や勝利よりも『失敗』から学ぶことが多い…"
    author: "ジョルノ・ジョバァーナ（ジョジョの奇妙な冒険）"